### ISSUE TITLE
Using plotenvelope() on a GLMM with offset

### ISSUE THREAD

**Issue by DEHewitt** [dwarton/ecostats#2]
Hi Dave,

I am trying to use `plotenvelope()` (which I think is an awesome function!) on a GLMM I have fit with `lme4`, as follows:
```
 catch.12 <- glmer(catch ~ zone + temp + dist_mouth + month + (1|site_name) + offset(log(soak/24)), 
                  family = poisson, data = catch)
plotenvelope(catch.12)
```
But I get the error
```
Error in offset(log(soak/24)) : object 'soak' not found
Error: $ operator is invalid for atomic vectors
```
I'm not sure if it's relevant, but I am modelling the `catch` of crabs in different zones in a marine park (`zone`). `soak` is how long each crab trap was in the water for (in hours).

Thanks for your help!
Dan

**Comment by dwarton** [comment]
thanks Dan!  I think this is fixed now (?)
